name: add_comment_and_label
on: [push, pull_request]
jobs:
  add_comment_and_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - name: Upgrade to Python 3.8
        # shell: bash
        run: sudo update-alternatives --install /usr/bin/python python ${pythonLocation}/bin/python3.8 10
      - run: pip install github3.py
      # - run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      # - run: git diff origin/master --name-only > git_diff.txt
      - name: Add a comment and a label
        shell: python
        run: |
          import os
          import sys
          from github3 import login
          print(sys.version_info)
          print("\n".join(f"{key}: {value}" for key, value in sorted(os.environ.values())))
          # print(os.environ)
          gh = login(token=secrets.GITHUB_TOKEN)
          print(gh.name)
          print(gh.login)
          print(gh.followers_count)
