name: git_diff
on: [push, pull_request]
jobs:
  git_diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: git diff
      - run: git diff --name-only
      - run: git diff --name-only > git_diff.txt
      - id: git_diff
        run: echo "##[set-output name=git_diff;]$(git diff --name-only)"
      - shell: python
        run: |
          print(0)
          with open("git_diff.txt") as in_file:
              print(in_file.read())
          print(1)
